package com.infinite.titan.models;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    // ID generated by the database
    private Long id;

    // UserEntity ID created by controller
    private String userId;

    // Username
    private String username;

    // Password
    private String password;

    // First name
    private String firstName;

    // Last name
    private String lastName;

    // Email
    private String email;

    // Role
    private Role role;

    // Account created date
    private LocalDateTime accountCreated;

    // Last login date
    private LocalDateTime lastLogin;

    // Profile picture URL
    private String profilePictureUrl;

    // Date of birth
    private LocalDateTime dateOfBirth;

    // Gender
    private String gender;
}