package com.infinite.titan.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "blog_posts")
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BlogPostEntity {

    // ID generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Title of the blog post
    @NotBlank(message = "Title is required")
    private String title;

    // Content of the blog post
    @NotBlank(message = "Content is required")
    @Lob // Large Object to store larger text
    private String content;

    // Author of the blog post (assuming author is just a name here for simplicity)
    @NotBlank(message = "Author name is required")
    private String authorName;

    // Date when the blog post was created
    @NotNull(message = "Creation date is required")
    private LocalDateTime createdDate;

    // Date when the blog post was last updated
    private LocalDateTime updatedDate;

    // Status of the blog post (e.g., published, draft)
    @NotBlank(message = "Status is required")
    private String status;
}